"""Add icon_url column to customer table

Revision ID: 3cedadb2b4df
Revises: c5b15a92ef72
Create Date: 2025-09-18 12:48:11.259729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cedadb2b4df"
down_revision: Union[str, Sequence[str], None] = "c5b15a92ef72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('icon_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'icon_url')
    # ### end Alembic commands ###
